baseURL = 'https://novelwaters.com/'
languageCode = 'en-us'
title = 'Novel Waters'

[params]
CompanyName = 'Novel Waters'
repoName = 'novelWaters'
description = 'Fiction, poetry and essays from the tide line.'
email = 'hello@novelwaters.com'

[environments.development]
baseURL = 'http://localhost:1313/'

[environments.production]
baseURL = 'https://novelwaters.com/'

[[menus.main]]
name = 'About'
url = '/about/'
weight = 10

[[menus.main]]
name = 'Fiction & Poetry'
url = '/fiction-and-poetry/'
weight = 20

[[menus.main]]
name = 'NonFiction'
url = '/nonfiction/'
weight = 30

[[menus.main]]
name = 'Recommendations'
url = '/recommendations/'
weight = 40

[[menus.main]]
name = 'Contact'
url = '/contact/'
weight = 50
