backend:
  name: github
  repo: jasonsutter87/novelwaters
  branch: master

publish_mode: editorial_workflow

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  # Fiction & Poetry
  - label: "Fiction & Poetry"
    name: "fictionAndPoetry"
    folder: "content/fiction-and-poetry"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Category", name: "category", widget: "select", options: ["Fiction", "Poetry"] }
      - { label: "Read time (e.g. 9 min)", name: "read", widget: "string", required: false }
      - { label: "Excerpt", name: "excerpt", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }

  # NonFiction
  - label: "NonFiction"
    name: "nonfiction"
    folder: "content/nonfiction"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Category", name: "category", widget: "select", options: ["Essay", "Column", "Reportage"] }
      - { label: "Read time (e.g. 9 min)", name: "read", widget: "string", required: false }
      - { label: "Excerpt", name: "excerpt", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }

  # Pages
  - label: "Pages"
    name: "pages"
    folder: "content"
    create: false
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Page Title (SEO)", name: "PageTitle", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
